brew_cask_packages:
  - alacritty
  - claude-code
  - docker
  - font-jetbrains-mono
  - fuwari # スクリーンショットを付箋にする
  - google-chrome
  - google-japanese-ime
  - notion
  - obsidian
  - postman
  - raycast
  - visual-studio-code

brew_job_cask_packages:
  - iTerm2
  - licecap # gif 作成
  - slack

brew_extra_cask_packages:
  - discord
  - shotcut # 動画編集
  - steam
